use std::collections::HashMap;

use crate::{backend::Backend, expdesc::{ExpType::self, StmtType}, internals::{q4r_expressions, q4r_functions, q4r_statements, q4r_variables}, signature::Signature};

/// Trait used by the support modules that generate code
/// 
/// Provides helper methods to parse the tokens/signatures generated by the lexer and the first parse.
pub trait Codegen<'a>{
    fn parse_expr(backend: &mut Backend<'a>) -> ExpType<'a>{
        q4r_expressions::parse_expr(backend)
    }

    fn parse_primary(backend: &mut Backend<'a>) -> ExpType<'a>{
        q4r_expressions::parse_primary(backend)
    }

    fn relational_statement(backend: &mut Backend<'a>) -> StmtType<'a>{
        q4r_statements::relational_statement(backend)
    }

    fn loop_statement(backend: &mut Backend<'a>) -> StmtType<'a>{
        q4r_statements::loop_statement(backend)
    }

    fn var_statement(backend: &mut Backend<'a>, is_pointer: bool) -> StmtType<'a>{
        q4r_variables::var_statement(backend, is_pointer)
    }

    fn assign_statement(backend: &mut Backend<'a>) -> ExpType<'a>{
        q4r_statements::assign_statement(backend)
    }

    fn fun_declaration(backend: &mut Backend<'a>, is_extern: bool) -> StmtType<'a>{
        q4r_functions::fun_declaration(backend, is_extern)
    }

    fn fun_call(backend: &mut Backend<'a>) -> ExpType<'a>{
        q4r_functions::fun_call(backend)
    }

    fn generate_headers(&mut self, signatures: &HashMap<String, Signature>) -> &mut Self;

    fn generate(&mut self, backend: &mut Backend<'a>) -> Vec<u8>;
}