use std::collections::HashMap;

use crate::{backend::Backend, expdesc::{ComparisonDeclaration, DeclType, ExpOperator, ExpType::self, FunCall, FunDeclaration, VarDeclaration}, internals::{q4r_expressions, q4r_functions, q4r_statements, q4r_variables}, signature::{Signature}};

/// Trait used by the support modules that generate code
/// 
/// Provides helper methods to parse the tokens/signatures generated by the lexer and the first parse.
pub trait Codegen<'a>{
    fn expression(backend: &mut Backend<'a>) -> ExpType<'a>{
        q4r_expressions::expression(backend)
    }

    fn mount_expression(backend: &mut Backend<'a>) -> ExpOperator<'a>{
        q4r_expressions::mount_expression(backend)
    }

    fn comparison_declaration(backend: &mut Backend<'a>) -> ComparisonDeclaration<'a>{
        q4r_statements::relational_statement(backend)
    }

    fn loop_declaration(backend: &mut Backend<'a>) -> DeclType<'a>{
        q4r_statements::loop_statement(backend)
    }

    fn var_declaration(backend: &mut Backend<'a>, is_pointer: bool) -> VarDeclaration<'a>{
        q4r_variables::var_declaration(backend, is_pointer)
    }

    fn var_callee(backend: &mut Backend<'a>) -> ExpType<'a>{
        q4r_variables::var_callee(backend)
    }

    fn fun_declaration(backend: &mut Backend<'a>, is_extern: bool) -> FunDeclaration<'a>{
        q4r_functions::fun_declaration(backend, is_extern)
    }

    fn fun_call(backend: &mut Backend<'a>) -> FunCall<'a>{
        q4r_functions::fun_call(backend)
    }

    fn generate_headers(&mut self, signatures: &HashMap<String, Signature>) -> &mut Self;

    fn generate(&mut self, backend: &mut Backend<'a>) -> Vec<u8>;
}