use std::collections::HashMap;

use crate::{backend::Backend, expdesc::{ComparisonDeclaration, DeclType, ExpLiteral, ExpOperator, ExpType::self, FunDeclaration, ForLoopDeclaration, VarDeclaration}, helper::parse_str, signature::{DecKind, Literal, Operator, Signature, Type::{self, Void}}, tokens::{VoidstarToken, VoidstarTokenTypes}};

/// Trait used by the support modules that generate code
/// 
/// Provides helper methods to parse the tokens/signatures generated by the lexer and the first parse.
pub trait Codegen<'a, B>{
    fn end(backend: &mut Backend<'a>) -> bool{
        backend.cursor >= backend.tokens.len()
    }
    
    fn expect(expected: VoidstarTokenTypes, backend: &mut Backend<'a>){
        backend.cursor += 1;
        if backend.cursor < backend.tokens.len() &&
            backend.tokens[backend.cursor].token_type != expected{ 
            panic!("found {:#?} instead of {:#?}", backend.tokens[backend.cursor].token_type, expected) 
        }
    }

    fn lookahead(backend: &mut Backend<'a>) -> VoidstarToken{
        if backend.cursor+1 < backend.tokens.len(){
            return backend.tokens[backend.cursor+1]
        }
        backend.tokens[backend.cursor]
    }

    fn signed_number(backend: &mut Backend<'a>) -> ExpLiteral{
        let sign = &backend.source[backend.tokens[backend.cursor].start..backend.tokens[backend.cursor].end];
        backend.cursor += 1;

        let number = &backend.source[backend.tokens[backend.cursor].start..backend.tokens[backend.cursor].end];
        let bytes = [sign, number].concat();
        
        ExpLiteral { val: Literal::to_literal(&bytes, VoidstarTokenTypes::Int) }
    }

    fn expression(backend: &mut Backend<'a>) -> ExpType<'a>{
        let current = backend.tokens[backend.cursor];
        let expression_type = Self::lookahead(backend).token_type;

        let mut subexpressions: Vec<ExpType<'_>> = Vec::new();

        // recurses back if a subexpression is detected
        // revisit this later
        if current.token_type == VoidstarTokenTypes::OpenBraces{
            backend.cursor += 1;
            subexpressions.push(Self::expression(backend));
        }

        match current.token_type{
            VoidstarTokenTypes::IntLiteral
            |VoidstarTokenTypes::FloatLiteral
            |VoidstarTokenTypes::BoolLiteral
            |VoidstarTokenTypes::CharLiteral => {
                if Operator::is_comparative(expression_type) || Operator::is_arithmetic(expression_type){
                    let left: &[u8];
                    let right: &[u8];
                    let operator;
                    
                    let lstart = backend.tokens[backend.cursor].start;
                    
                    while !(Operator::is_comparative(backend.tokens[backend.cursor].token_type) ||
                            Operator::is_arithmetic(backend.tokens[backend.cursor].token_type)){
                            backend.cursor+=1;
                    }
                    
                    let lend = backend.tokens[backend.cursor-1].end;
                    left = &backend.source[lstart..lend];

                    operator = Operator::map(backend.tokens[backend.cursor].token_type);

                    backend.cursor+=1;
                    let rstart = backend.tokens[backend.cursor].start;

                    while Operator::is_legal(backend.tokens[backend.cursor].token_type){ 
                        backend.cursor+=1;
                    }

                    let rend = backend.tokens[backend.cursor-1].end;
                    right = &backend.source[rstart..rend];

                    return ExpType::OperativeExp(ExpOperator{ left, operator, right })
                }
            
                let bytes_value = &backend.source[current.start..current.end];
                
                ExpType::LiteralExp(ExpLiteral{
                    val: Literal::to_literal(bytes_value, Literal::from_literal(current.token_type))
                })
            },

            VoidstarTokenTypes::Ident => {
                if Operator::is_arithmetic(expression_type) || Operator::is_comparative(expression_type){
                    let left: &[u8];
                    let right: &[u8];
                    let operator;
                    
                    let lstart = backend.tokens[backend.cursor].start;
                    
                    while !(Operator::is_comparative(backend.tokens[backend.cursor].token_type) ||
                            Operator::is_arithmetic(backend.tokens[backend.cursor].token_type)){
                            backend.cursor+=1;
                    }
                    
                    let lend = backend.tokens[backend.cursor-1].end;
                    left = &backend.source[lstart..lend];

                    operator = Operator::map(backend.tokens[backend.cursor].token_type);

                    backend.cursor+=1;
                    let rstart = backend.tokens[backend.cursor].start;

                    while Operator::is_legal(backend.tokens[backend.cursor].token_type){ 
                        backend.cursor+=1;
                    }

                    let rend = backend.tokens[backend.cursor-1].end;
                    right = &backend.source[rstart..rend];

                    return ExpType::OperativeExp(ExpOperator{ left, operator, right })
                }
                let bytes_value = &backend.source[current.start..current.end];

                ExpType::LiteralExp(ExpLiteral { 
                    val: Literal::to_literal(bytes_value, current.token_type)
                })
            },

            _ => panic!("illegal expression argument `{:#?}`", current.token_type)
        }
    }

    fn comparison_declaration(backend: &mut Backend<'a>) -> ComparisonDeclaration<'a>{
        backend.cursor+=1;
        let expression = Self::expression(backend);
        
        ComparisonDeclaration { kind: DecKind::If, expression }
    }

    fn loop_declaration(backend: &mut Backend<'a>) -> DeclType<'a>{
        backend.cursor += 1;
        let iterator = &backend.source[backend.tokens[backend.cursor].start..backend.tokens[backend.cursor].end];

        backend.cursor += 2;
        let init_expression = Self::expression(backend);

        if Self::lookahead(backend).token_type == VoidstarTokenTypes::SemiColon{
            backend.cursor += 2;
            
            let exp = Self::expression(backend);

            backend.cursor += 1;
            let incrementer = Self::signed_number(backend).val;

            DeclType::ForLoopDecl(ForLoopDeclaration { 
                kind: DecKind::For, iterator, initializer: init_expression, exp, incrementer 
            })

        }else{
            DeclType::WhileLoopDecl(ComparisonDeclaration { kind: DecKind::While, expression: init_expression })
        }
    }

    fn var_declaration(backend: &mut Backend<'a>) -> VarDeclaration<'a>{
        let var_type = backend.tokens[backend.cursor].token_type;
        let mut ty = Type::map(backend.tokens[backend.cursor].token_type);
        if ty.eq(&Type::Bool){ ty = Type::Int }

        Self::expect(VoidstarTokenTypes::Ident, backend);

        let ident = &backend.source[
            backend.tokens[backend.cursor].start..backend.tokens[backend.cursor].end
        ];

        let val: Literal = if Self::lookahead(backend).token_type == VoidstarTokenTypes::Equals{
            backend.cursor+=2;
            let current = backend.tokens[backend.cursor];
            let byted_val;

            let literal = match current.token_type{
                VoidstarTokenTypes::Ident => { 
                    byted_val = &backend.source[current.start..current.end];
                    Literal::to_identifier(byted_val.to_vec())
                },

                VoidstarTokenTypes::IntLiteral
                | VoidstarTokenTypes::FloatLiteral
                | VoidstarTokenTypes::CharLiteral
                | VoidstarTokenTypes::BoolLiteral => {
                    byted_val = &backend.source[current.start..current.end];
                    Literal::to_literal(byted_val, var_type)
                },
                
                _ => panic!("bad variable declaration {:#?}", current)
            };
            literal
        }else{
            Literal::to_literal(&ty.default_literal().to_byte_span(), var_type)
        };

        backend.cursor+=1;
        VarDeclaration { ty, ident, val: ExpType::LiteralExp(ExpLiteral{ val }) }
    }

    fn fun_declaration(backend: &mut Backend<'a>) -> FunDeclaration<'a>{
        Self::expect(VoidstarTokenTypes::Ident, backend);
        let ident = &backend.source[
            backend.tokens[backend.cursor].start..backend.tokens[backend.cursor].end
        ];

        Self::expect(VoidstarTokenTypes::OpenParents, backend);
        let mut params: Vec<VarDeclaration> = Vec::new();

        backend.cursor+=1;
        while backend.tokens[backend.cursor].token_type != VoidstarTokenTypes::CloseParents{
            match backend.tokens[backend.cursor].token_type{
                VoidstarTokenTypes::Int
                | VoidstarTokenTypes::Float
                | VoidstarTokenTypes::Char
                | VoidstarTokenTypes::Bool => {
                    let declaration: VarDeclaration<'a> = Self::var_declaration(backend);

                    params.push(declaration);
                },

                VoidstarTokenTypes::Comma | VoidstarTokenTypes::Void => backend.cursor+=1,
                
                _ => panic!("unknown symbol as a parameter of `{}`", str::from_utf8(ident).unwrap_or("unknown"))
            }
        }

        let returns = if Type::has(Self::lookahead(backend).token_type){
            backend.cursor += 1;
            Type::map(backend.tokens[backend.cursor].token_type)
        } else {
            Type::Void
        };

        Self::expect(VoidstarTokenTypes::OpenBraces, backend);
        
        FunDeclaration { returns, ident, params }
    }

    fn generate_headers(&mut self, signatures: &HashMap<String, Signature>) -> &mut Self;

    fn generate(&mut self, backend: &mut Backend<'a>) -> Vec<u8>;
}