use std::collections::HashMap;

use crate::{expdesc::{ComparisonDeclaration, ExpLiteral, ExpOperator, ExpType::self, FunDeclaration, VarDeclaration}, signature::{DecKind, Literal, Operator, Signature, Type::{self, Void}}, tokens::{VoidstarToken, VoidstarTokenTypes}};

/// Trait used by the support modules that generate code
/// 
/// Provides helper methods to parse the tokens/signatures generated by the lexer and the first parse.
pub trait CodeGen{
    fn end(tokens: &[VoidstarToken], cursor: &mut usize) -> bool{
        *cursor >= tokens.len()
    }
    
    fn expect(expected: VoidstarTokenTypes, tokens: &[VoidstarToken], cursor: &mut usize){
        *cursor += 1;
        if *cursor < tokens.len() &&
            tokens[*cursor].token_type != expected{ 
            panic!("found {:#?} instead of {:#?}", tokens[*cursor].token_type, expected) 
        }
    }

    fn lookahead(tokens: &[VoidstarToken], cursor: &usize) -> VoidstarToken{
        if *cursor+1 < tokens.len(){
            return tokens[*cursor+1]
        }
        tokens[*cursor]
    }

    fn expression<'a>(tokens: &[VoidstarToken], source: &'a[u8], cursor: &mut usize) -> ExpType<'a>{
        let current = tokens[*cursor].token_type;
        let expression_type = Self::lookahead(tokens, cursor).token_type;

        let mut subexpressions: Vec<ExpType<'_>> = Vec::new();

        // recurses back if a subexpression is detected
        if current == VoidstarTokenTypes::OpenBraces{
            *cursor += 1;
            subexpressions.push(Self::expression(tokens, source, cursor));
        }

        if Operator::is_comparative(expression_type) || Operator::is_arithmetic(expression_type){
            let left: &[u8];
            let right: &[u8];
            let operator;
            
            let lstart = tokens[*cursor].start;
            
            while !(Operator::is_comparative(tokens[*cursor].token_type) ||
                    Operator::is_arithmetic(tokens[*cursor].token_type)){
                    *cursor+=1;
            }
            
            let lend = tokens[*cursor-1].end;
            left = &source[lstart..lend];

            operator = Operator::map(tokens[*cursor].token_type);

            *cursor+=1;
            let rstart = tokens[*cursor].start;

            while Operator::is_legal(tokens[*cursor].token_type){ 
                *cursor+=1;
            }

            let rend = tokens[*cursor-1].end;
            right = &source[rstart..rend];

            return ExpType::OperativeExp(ExpOperator{ left, operator, right })
        }
        let literal_type = Type::map_literal_token(current).as_token_type();
        
        ExpType::LiteralExp(ExpLiteral{
            val: Literal::to_literal(&source[tokens[*cursor].start..tokens[*cursor].end], literal_type)
        })
    }

    fn comparison_declaration<'a>(tokens: &[VoidstarToken], source: &'a[u8], cursor: &mut usize) -> ComparisonDeclaration<'a>{
        let kind = DecKind::map(tokens[*cursor].token_type);
        *cursor+=1;
        let expression = Self::expression(tokens, source, cursor);
        
        ComparisonDeclaration { kind, expression }
    }

    fn var_declaration<'a>(tokens: &[VoidstarToken], source: &'a[u8], cursor: &mut usize) -> VarDeclaration<'a>{
        let var_type = tokens[*cursor].token_type;
        let mut ty = Type::map(tokens[*cursor].token_type);
        if ty.eq(&Type::Bool){ ty = Type::Int }

        Self::expect(VoidstarTokenTypes::Ident, tokens, cursor);

        let ident = &source[tokens[*cursor].start..tokens[*cursor].end];

        let val: Literal = if Self::lookahead(tokens, cursor).token_type == VoidstarTokenTypes::Equals{
            *cursor+=2;
            let current = tokens[*cursor];
            let byted_val;

            // GABS' NOTE error is prob here (09/16::16:48)

            match current.token_type{
                VoidstarTokenTypes::Ident => { 
                    println!("{:?}", current);
                    byted_val = &source[current.start..current.end];
                    println!("{:#?}", byted_val);
                },

                VoidstarTokenTypes::IntLiteral
                | VoidstarTokenTypes::FloatLiteral
                | VoidstarTokenTypes::CharLiteral
                | VoidstarTokenTypes::BoolLiteral => byted_val = &source[tokens[*cursor].start..tokens[*cursor].end],
                
                _ => panic!("bad variable declaration {:#?}", current)
            }

            Literal::to_literal(byted_val, var_type)
        }else{
            Literal::to_literal(&ty.default_literal().to_byte_span(), var_type)
        };

        *cursor+=1;
        VarDeclaration { ty, ident, val: ExpType::LiteralExp(ExpLiteral{ val }) }
    }

    fn fun_declaration<'a>(tokens: &[VoidstarToken], source: &'a[u8], cursor: &mut usize) -> FunDeclaration<'a>{
        Self::expect(VoidstarTokenTypes::Ident, tokens, cursor);
        let ident = &source[tokens[*cursor].start..tokens[*cursor].end];

        Self::expect(VoidstarTokenTypes::OpenParents, tokens, cursor);
        let mut params: Vec<VarDeclaration> = Vec::new();

        *cursor+=1;
        while tokens[*cursor].token_type != VoidstarTokenTypes::CloseParents{
            match tokens[*cursor].token_type{
                VoidstarTokenTypes::Int
                | VoidstarTokenTypes::Float
                | VoidstarTokenTypes::Char
                | VoidstarTokenTypes::Bool => {
                    let declaration: VarDeclaration<'a> = Self::var_declaration(tokens, source, cursor);

                    params.push(declaration);
                },

                VoidstarTokenTypes::Comma | VoidstarTokenTypes::Void => *cursor+=1,
                
                _ => panic!("unknown symbol as a parameter of `{}`", str::from_utf8(ident).unwrap_or("unknown"))
            }
        }

        *cursor+=1;
        let returns = Type::map(tokens[*cursor].token_type);

        Self::expect(VoidstarTokenTypes::OpenBraces, tokens, cursor);
        
        FunDeclaration { returns, ident, params }
    }

    fn generate_headers(&mut self, signatures: HashMap<String, Signature>) -> &mut Self;

    fn generate<'a>(&mut self, tokens: &'a[VoidstarToken], source: &'a[u8], cursor: &mut usize) -> Vec<u8>;
}