use crate::{expdesc::{FunDeclaration, VarDeclaration}, signatures::{Literal, Type::{self, Void}}, tokens::{VoidstarToken, VoidstarTokenTypes}};

/// Trait used by the support modules that generate code
/// 
/// Provides helper methods to parse the tokens/signatures generated by the lexer and the first parse.
pub trait CodeGen{
    fn expect(expected: VoidstarTokenTypes, tokens: &[VoidstarToken], cursor: &mut usize){
        *cursor += 1;
        if *cursor < tokens.len() &&
            tokens[*cursor].token_type != expected{ 
            panic!("found {:#?} instead of {:#?}", tokens[*cursor].token_type, expected) 
        }
    }

    fn next(tokens: &[VoidstarToken], cursor: &usize) -> VoidstarToken{
        if *cursor+1 > tokens.len(){ return tokens[*cursor] }
        tokens[*cursor+1]
    }

    fn var_declaration<'a>(tokens: &[VoidstarToken], source: &'a[u8], cursor: &mut usize) -> VarDeclaration<'a>{
        let ty = Type::map(tokens[*cursor].token_type);
        Self::expect(VoidstarTokenTypes::Ident, tokens, cursor);

        let ident = &source[tokens[*cursor].start..tokens[*cursor].end];
        let val: &'a[u8] = if Self::next(tokens, cursor).token_type == VoidstarTokenTypes::Equals{
            *cursor+=2;
            &source[tokens[*cursor].start..tokens[*cursor].end]
        }else{
            b"void"
        };

        *cursor+=1;
        VarDeclaration { ty, ident, val }
    }

    fn fun_declaration<'a>(tokens: &[VoidstarToken], source: &'a[u8], cursor: &mut usize) -> FunDeclaration<'a>{
        Self::expect(VoidstarTokenTypes::Ident, tokens, cursor);
        let ident = &source[tokens[*cursor].start..tokens[*cursor].end];

        Self::expect(VoidstarTokenTypes::OpenParents, tokens, cursor);
        let mut params: Vec<&[u8]> = Vec::new();

        while tokens[*cursor].token_type != VoidstarTokenTypes::CloseParents{
            match tokens[*cursor].token_type{
                VoidstarTokenTypes::Int
                | VoidstarTokenTypes::Float
                | VoidstarTokenTypes::Char
                | VoidstarTokenTypes::Bool => {
                    let declaration: VarDeclaration<'a> = Self::var_declaration(tokens, source, cursor);
                    params.extend([
                        declaration.ty.to_byte_span(),
                        declaration.ident,
                        declaration.val
                    ]);
                },

                VoidstarTokenTypes::Comma | VoidstarTokenTypes::Void => continue,
                
                _ => panic!("unknown symbol as a parameter of `{}`", str::from_utf8(ident).unwrap_or("unknown"))
            }
        }

        todo!()
    }

    fn generate(&mut self) -> Vec<u8>;
}